name: box-xray-tun-v2.1

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github"
      - "README.md"
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get repository name
        id: get_repo_name
        run: echo "REPO_NAME=$(basename $(git rev-parse --show-toplevel))" >> $GITHUB_ENV

      - name: Update update.json
        run: |
          version=$(grep -oP 'version=\K[^ ]+' module.prop)
          versionCode=$(grep -oP 'versionCode=\K[^ ]+' module.prop)

          echo '{
            "version": "'"${version}"'",
            "versionCode": "'"${versionCode}"'",
            "zipUrl": "https://github.com/coomsn/${{ env.REPO_NAME }}/releases/download/'"${version}"'/box-xray-tun-'${version}'.zip",
            "changelog": "https://github.com/coomsn/${{ env.REPO_NAME }}/raw/main/CHANGELOG.md"
          }' > update.json

      - name: Commit and push update.json
        run: |
          git config --local user.name "coomsn"
          git config --local user.email "acstudycn@gmail.com"
          git add update.json
          git commit -m "Update update.json for version $(grep -oP 'version=\K[^ ]+' module.prop)" || true
          git push -f origin main

      - name: Run build.sh
        run: sh build.sh

      - name: Extract version from filename
        id: extract_version
        run: |
          zip_file=$(ls box-xray-tun-v*.zip)
          version=$(echo "$zip_file" | sed -E 's/box-xray-tun-v(.*).zip/v\1/')
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Read release notes from CHANGELOG.md
        id: get_release_notes
        run: |
          RELEASE_NOTES=$(cat CHANGELOG.md)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload release
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        with:
          tag_name: ${{ env.VERSION }}
          files: box-xray-tun-v*.zip
          body: ${{ env.RELEASE_NOTES }}
          prerelease: false
          draft: false # 确保发布不是草稿
          overwrite: true # 确保覆盖已有发布
          generate_release_notes: false
